#!/bin/bash

## Copyright (C) 2018 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## Keep the command trace: it is this script's diagnostic output.
set -x
set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
shopt -s inherit_errexit
shopt -s shift_verbose

terminal_emulator_window_title="sdwdate Log Viewer"
export terminal_emulator_window_title

/usr/libexec/helper-scripts/terminal-wrapper "leaprun sdwdate-log-viewer"
